# define the root directory that all other paths are relative to
root_dir: &root_dir ../../data/transfer/preprocess/
data_dir: !path [*root_dir, "superpixels", "patches"]
mask_dir: !path [*root_dir, "superpixels", "masks"]
target_dir: !path [*root_dir, "masks"]
test_dir: !path [*root_dir, "tifs"]
out_dir: &out_dir !path [*root_dir, "output"]
ckpt_path: checkpoints/unet-UN-132-epoch=11-val_dice=0.96.ckpt
validation_input_dir: !path [*root_dir, "composite", "tifs"]
validation_target_dir: !path [*root_dir, "composite", "masks"]
input_channels: 1 
learning_rate: 1.e-5
batch_size: 40 
epochs: 10
device: cuda # Example: 'cpu' or 'cuda'

classes:
  - "bg"
  - "625"
  - "605"
weights:
  - 1
  - 1
  - 1

gpus: 1 # How many gpus to use
precision: '16-mixed' # 16, 32, 64, 'full', 'double', '16-mixed', '16-bf16'
accelerator: 'auto' # 'cpu', 'gpu', 'tpu', 'amp', 'auto'
encoder_path: !path [*root_dir, '..', 'encoder', 'best_model.ckpt']
k_folds: 5 # Number of folds to perform during validation step
debug:
  enable: false # prefer to pass the debug flag at the cli
  fast: true
  epochs: 5
  train_batches: 0.05
  val_batches: 0.01

