device: cpu
directories:
  root: &D:\CZI_scope\code\ml_models\unet\segmentation
  data: *root\data
  results: *root\results
  model: *root\model
  inputs: D:\CZI_scope\code\preprocess_training\tifs
  targets: D:\CZI_scope\code\preprocess_training\masks
  create: true
files:
  checkpoint: unet.pth.tar 
  dataset: dataset.pth.tar
training:
  batch_size: 16
  epochs: 10
  lr: 0.001
  train_ratio: 0.8
  optimizer: adam
  scheduler: plateau
  optimizer_params: {}
  scheduler_params:
    patience: 3
    factor: 0.1
model:
  in_channels: 1
  out_channels: 3
  features:
    - 64
    - 128
    - 256
    - 512
plotting:
  save: true
  classes:
    - background
    - "625"
    - "605"
  labels:
    - 0
    - 1
    - 2
preprocessing:
  inputs:
    targets: 
      - image
      - mask
    transforms:
      ToFloat:
        p: 1
      LongestMaxSize:
        p: 1
      PadIfNeeded:
        p: 1
        max_size: 256
      RandomBrightnessConstrast: {}
      GaussNoise:
        var_limit:
          - 1.e-4
          - 1.e-3
  targets:
    targets:
      - none
    transforms:
      custom:
        apply_on_validation: true
        name: to_tensor
        args:
          - 'y'
        