# define the root directory that all other paths are relative to
root_dir: &root_dir .
data_dir: ../../data/transfer/preprocess/tifs
out_dir: !path [*root_dir, 'output']
input_channels: 1
embedding_dim: 8
learning_rate: 1.e-4
batch_size: 32
epochs: 2
device: cuda # Example: 'cpu' or 'cuda'data_dir: *root_dir\data
resize: [128, 128] # resize the input image
weights:
  "605": 0.25
  "625": 0.75
loss_scale: 100 # What to scale the loss by
