device = 'cuda'

[directories]
root = '.'
data = 'data'
results = 'results'
inputs = '/scratch/general/nfs1/u0977428/transfer/preprocess/tifs/'
targets = '/scratch/general/nfs1/u0977428/transfer/preprocess/masks/'
model = 'model'
create = true

[files]
model = 'model.tar'
dataset = 'dst.tar'

[training]
batch_size = 32
epochs = 16
lr = 1e-3
train_ratio = 0.8 # 80% of the data is used for training
optimizer = 'adam'
scheduler = 'plateau'

[training.optimizer_params]
# Any parameter that is not specified will be set to the default value

[training.scheduler_params]
# Any parameter that is not specified will be set to the default value
patience = 2
factor = 0.15


[model]
in_channels = 1
out_channels = 3
features = [64, 128, 256, 512]

[plotting]
save = true
classes = ['background', '625', '605']
labels = [0, 1, 2]

    
        
